### ISSUE TITLE
Suggest: Cache ShadowHeater to remove after the iteration

### ISSUE THREAD

**Issue by No3371** [yasenfire/CoolHome#1]
Current implementation remove items during iteration, which will throw. A better way would be a new list to keep items to remove, and actually remove them after the iteration is done.
https://github.com/yasenfire/CoolHome/blob/23ca6a0352f50593ce40794734ed588d083aec85/Main/WarmingWalls/WarmingWalls.cs#L126

```
[22:12:21.067] [Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at CoolHome.WarmingWalls.Update()
   at Trampoline_VoidThisCoolHome.WarmingWallsUpdate(IntPtr , Il2CppMethodInfo* )
```

**Comment by yasenfire** [comment]
Agree. Solved
